database:
  build: ./postgresql

ldap:
  build: ./ldap

geoserver:
  image: geoserver

proxy:
  image: security-proxy
  ports:
    - "8080:8080"
  links:
    - database
    - ldap
    - cas
    - mapfishapp
    - extractorapp
    - ldapadmin
    - geonetwork
    - header
    - geoserver
  volumes:
    - ./datadir:/etc/georchestra

cas:
  image: cas
  links:
    - ldap
  volumes:
    - ./datadir:/etc/georchestra

mapfishapp:
  image: mapfishapp
  links:
    - database
  volumes:
    - ./datadir:/etc/georchestra

extractorapp:
  image: extractorapp
  links:
    - database
  volumes:
    - ./datadir:/etc/georchestra

header:
  image: header
  volumes:
    - ./datadir:/etc/georchestra

ldapadmin:
  image: ldapadmin
  links:
    - database
    - ldap
  volumes:
    - ./datadir:/etc/georchestra

geonetwork:
  image: geonetwork
  ports:
    - "1099:1099"
  links:
    - database
    - ldap
  volumes:
    - ./datadir:/etc/georchestra
